import Button from "../../button/Button";

function PatientInfoSummary() {
  return (
    <div className="col-span-2 flex flex-col p-6 bg-white rounded-lg shadow-md overflow-auto">
      <h2 className="text-2xl font-bold mb-4">
        Patient Summary
        <span className="text-sm font-medium text-gray-500">
          {" "}
          Generated by AI
        </span>
      </h2>
      <div className="flex-1">
        This is wehere summary would bcom
      </div>
      <div className="flex justify-end">
        <Button
          className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-md"
          text="View Detailed Analysis"
        />
      </div>
    </div>
  );
}

export default PatientInfoSummary;
